### ISSUE TITLE
'make deps' failed

### ISSUE THREAD

**Issue by alexalouit** [andrewlow/v8ppc#130]
Trying to compile a functional version of v8+nodejs for ppc 32 bits (PowerPC 750),
here is what I got:

````
$ git clone https://github.com/andrewlow/v8ppc.git v8
$ gclient config --spec "solutions = [{'name': 'v8', 'url': 'https://github.com/andrewlow/v8ppc.git'}]"; gclient sync

...

WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git" "/root/git/v8/test/test262/_gclient_harness_s5ncP5"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git" "/root/git/v8/test/test262/_gclient_harness_s5ncP5"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/googlemock.git" "/root/git/v8/testing/_gclient_gmock_N3d3Km"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/google/googletest.git" "/root/git/v8/testing/_gclient_gtest_stTKSk"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git" "/root/git/v8/test/test262/_gclient_harness_s5ncP5"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/tc39/test262.git" "/root/git/v8/test/test262/_gclient_data_DOi0A4"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/googlemock.git" "/root/git/v8/testing/_gclient_gmock_N3d3Km"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/google/googletest.git" "/root/git/v8/testing/_gclient_gtest_stTKSk"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git" "/root/git/v8/test/test262/_gclient_harness_s5ncP5"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/tc39/test262.git" "/root/git/v8/test/test262/_gclient_data_DOi0A4"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/googlemock.git" "/root/git/v8/testing/_gclient_gmock_N3d3Km"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/google/googletest.git" "/root/git/v8/testing/_gclient_gtest_stTKSk"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/chromium/src/third_party/WebKit/Source/platform/inspector_protocol.git" "/root/git/v8/third_party/WebKit/Source/platform/_gclient_inspector_protocol_98VD15"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/tc39/test262.git" "/root/git/v8/test/test262/_gclient_data_DOi0A4"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/googlemock.git" "/root/git/v8/testing/_gclient_gmock_N3d3Km"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/external/github.com/google/googletest.git" "/root/git/v8/testing/_gclient_gtest_stTKSk"' in /root/git failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=512m" "clone" "--no-checkout" "--progress" "--template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates" "https://chromium.googlesource.com/chromium/src/third_party/WebKit/Source/platform/inspector_protocol.git" "/root/git/v8/third_party/WebKit/Source/platform/_gclient_inspector_protocol_98VD15"' in /root/git failed; will retry after a short nap...
Syncing projects:  41% (10/24) v8/third_party/WebKit/Source/platform/inspector_protocol
[0:02:52] Still working on:
[0:02:52]   v8/build
[0:02:52]   v8/test/test262/data

[0:03:02] Still working on:
[0:03:02]   v8/build
[0:03:02]   v8/test/test262/data

[0:03:12] Still working on:
[0:03:12]   v8/build
[0:03:12]   v8/test/test262/data

[0:03:22] Still working on:
[0:03:22]   v8/build
[0:03:22]   v8/test/test262/data

[0:03:32] Still working on:
[0:03:32]   v8/build
[0:03:32]   v8/test/test262/data

[0:03:42] Still working on:
[0:03:42]   v8/build
[0:03:42]   v8/test/test262/data

[0:03:52] Still working on:
[0:03:52]   v8/build
[0:03:52]   v8/test/test262/data

[0:03:58] Still working on:
[0:03:58]   v8/build
[0:03:58]   v8/test/test262/data
Syncing projects:  45% (11/24) v8/build                                                
[0:04:58] Still working on:
[0:04:58]   v8/test/test262/data

[0:05:08] Still working on:
[0:05:08]   v8/test/test262/data

[0:05:18] Still working on:
[0:05:18]   v8/test/test262/data

[0:05:28] Still working on:
[0:05:28]   v8/test/test262/data

[0:05:38] Still working on:
[0:05:38]   v8/test/test262/data

[0:05:41] Still working on:
[0:05:41]   v8/test/test262/data
Syncing projects:  50% (12/24) v8/test/test262/data

v8/test/test262/harness (ERROR)
----------------------------------------
[0:00:07] Started.
[0:00:08] 
[0:00:08] running 'git -c core.deltaBaseCacheLimit=512m clone --no-checkout --progress --template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git /root/git/v8/test/test262/_gclient_harness_s5ncP5' in '/root/git'
[0:00:08] Cloning into '/root/git/v8/test/test262/_gclient_harness_s5ncP5'...
[0:00:08] warning: templates not found /usr/local/lib/python2.7/dist-packages/depot_tools/git-templates
[0:00:22] fatal: unable to access 'https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
[0:00:24] Cloning into '/root/git/v8/test/test262/_gclient_harness_s5ncP5'...
[0:00:24] warning: templates not found /usr/local/lib/python2.7/dist-packages/depot_tools/git-templates
[0:00:40] fatal: unable to access 'https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
[0:00:42] Cloning into '/root/git/v8/test/test262/_gclient_harness_s5ncP5'...
[0:00:42] warning: templates not found /usr/local/lib/python2.7/dist-packages/depot_tools/git-templates
[0:00:57] fatal: unable to access 'https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
[0:01:00] Cloning into '/root/git/v8/test/test262/_gclient_harness_s5ncP5'...
[0:01:00] warning: templates not found /usr/local/lib/python2.7/dist-packages/depot_tools/git-templates
[0:01:16] fatal: unable to access 'https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_scm.py", line 811, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_scm.py", line 1021, in _Run
    return gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_utils.py", line 526, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command git -c core.deltaBaseCacheLimit=512m clone --no-checkout --progress --template=/usr/local/lib/python2.7/dist-packages/depot_tools/git-templates https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git /root/git/v8/test/test262/_gclient_harness_s5ncP5 returned non-zero exit status 128 in /root/git
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/gclient", line 10, in <module>
    sys.exit(gclient.Main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 2000, in Main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 1778, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 1297, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_utils.py", line 936, in run
    self.item.run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 699, in run
    file_list)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_scm.py", line 160, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_scm.py", line 373, in update
    self._Clone(revision, url, options)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_scm.py", line 819, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: '/root/git/v8/test/test262/_gclient_harness_s5ncP5'
````

I'm not familiar with gconfig, any idea of what's happen?

Ubuntu 16.04.3 (nodejs from apt repo don't work).

**Comment by alexalouit** [comment]
Clone each repo manually in /root/git/v8/third_party did the trick.

Now I have

````
.gclient file in parent directory /root/git might not be the file you want to use
Syncing projects:  95% (23/24), done.                                                  

________ running '/usr/bin/python v8/gypfiles/landmines.py' in '/root/git'
Clobbering due to missing landmines file.

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s v8/buildtools/win/clang-format.exe.sha1' in '/root/git'
Traceback (most recent call last):
  File "/usr/local/bin/gclient", line 10, in <module>
    sys.exit(gclient.Main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 2000, in Main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 1778, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 1305, in RunOnDeps
    self.RunHooksRecursively(self._options)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 850, in RunHooksRecursively
    hook, cwd=self.root.root_dir, always=True)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_utils.py", line 281, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_utils.py", line 476, in CheckCallAndFilter
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/depot_tools/subprocess2.py", line 253, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 2] No such file or directory.
Check that /root/git or download_from_google_storage exist and have execution permission.
````

**Comment by alexalouit** [comment]
Using depot_roots from source instead of pip version, and compile git with openssl instead gnutls works.
